Build the tests with release=8 whenever it is possible
AdoptOpenJDK/openjdk-systemtest pull request #489
Opened 2024-09-23 18:21 UTC by fridrich

Fixes https://github.com/eclipse-openj9/openj9/issues/19888

The tests have to be built with release=8 in order to avoid calling the new overridden methods with covariant return types in java.nio.ByteBuffer/CharBuffer/LongBuffer, like position(int), rewind, flip...
The only source file that has to be built with source=1.8 and target=1.8 is the gnu/testlet/java/lang/Class/classInfo/getDeclaredMethod.java, because it requires sun.reflect.annotation.AnnotationType that is not visible using release=8 from jdk9+
The specifying of release="8", source="1.8" and target="1.8" allows ant 1.10.x to use either release if supported or the source/target if release is not supported.

2024-09-24 10:23 UTC, karianna commented
@fridrich Are you able to sign the Eclipse CLA?

2024-09-24 15:38 UTC, llxia commented
Thanks @fridrich for providing the fix. Could you try to sign ECA? https://github.com/adoptium/aqa-tests/blob/master/Contributing.md#eclipse-contributor-agreement

It should be a straightforward process. Unfortunately, we cannot accept the change without the ECA signed.

2024-09-24 15:40 UTC, llxia commented
@annaibm Please help to test this PR. Thanks

2024-09-24 15:48 UTC, pshipton commented
FYI the comment which I'll copy here.

[fridrich](https://github.com/fridrich) commented [Sep 23, 2024](https://github.com/eclipse-openj9/openj9/issues/19888#issuecomment-2369060838)

So, that pull request basically fixes the build of the mauve.jar, so that it works with the java 8. It is hanging in eclipsefdn/eca. I am not sure whether we (SUSE) have ever signed something like this. I also don't care to be credited, so anybody who has the right paperwork on file can submit that patch. I transfer automatically the copyright to anybody brave enough to get it integrated.

2024-09-24 17:48 UTC, fridrich commented
At the end, I signed it in my personal capacity. So it should be good I think.

2024-10-03 14:05 UTC, llxia commented
Quick update: We encountered other issues while upgrading to JDK 17 for compilation for all dependent jars (though `mauve.jar` is fine). This PR can't be merged until those issues are resolved.

2024-10-03 17:26 UTC, smlambert requested changes
Given the comment that it can't be merged, putting a request changes 'hold' on this one so that it is not accidentally merged ahead of the other issues are resolved (more details on the other issues referenced would be good to link to this @llxia )

2024-11-18 18:33 UTC, llxia approved these changes
LGTM

2024-11-18 18:34 UTC, llxia commented
@smlambert we are ready to merge this PR.

2024-11-18 18:36 UTC, smlambert approved these changes

2024-11-18 18:44 UTC, merged